package com.cc4j.serial;

/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'NdpSerial'
 * message type.
 */

public class NdpSerial extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 60;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 119;

    /** Create a new NdpSerial of size 21. */
    public NdpSerial() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new NdpSerial of the given data_length. */
    public NdpSerial(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial with the given data_length
     * and base offset.
     */
    public NdpSerial(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial using the given byte array
     * as backing store.
     */
    public NdpSerial(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial using the given byte array
     * as backing store, with the given base offset.
     */
    public NdpSerial(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public NdpSerial(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial embedded in the given message
     * at the given base offset.
     */
    public NdpSerial(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new NdpSerial embedded in the given message
     * at the given base offset and length.
     */
    public NdpSerial(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <NdpSerial> \n";
      try {
        s += "  [type=0x"+Long.toHexString(get_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [msg=";
        for (int i = 0; i < DEFAULT_MESSAGE_SIZE; i++) {
          s += "0x"+Long.toHexString(getElement_msg(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type
    //   Field type: short, signed
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type' is signed (true).
     */
    public static boolean isSigned_type() {
        return true;
    }

    /**
     * Return whether the field 'type' is an array (false).
     */
    public static boolean isArray_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'type'
     */
    public static int offset_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type'
     */
    public static int offsetBits_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'type'
     */
    public short get_type() {
        return (short)getUIntElement(offsetBits_type(), 8);
    }

    /**
     * Set the value of the field 'type'
     */
    public void set_type(short value) {
        setUIntElement(offsetBits_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'type'
     */
    public static int size_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'type'
     */
    public static int sizeBits_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msg
    //   Field type: byte[], signed
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msg' is signed (true).
     */
    public static boolean isSigned_msg() {
        return true;
    }

    /**
     * Return whether the field 'msg' is an array (true).
     */
    public static boolean isArray_msg() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'msg'
     */
    public static int offset_msg(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= DEFAULT_MESSAGE_SIZE) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msg'
     */
    public static int offsetBits_msg(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= DEFAULT_MESSAGE_SIZE) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'msg' as a byte[]
     */
    public byte[] get_msg() {
        byte[] tmp = new byte[DEFAULT_MESSAGE_SIZE];
        for (int index0 = 0; index0 < numElements_msg(0); index0++) {
            tmp[index0] = getElement_msg(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'msg' from the given byte[]
     */
    public void set_msg(byte[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_msg(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a byte) of the array 'msg'
     */
    public byte getElement_msg(int index1) {
        return (byte)getSIntElement(offsetBits_msg(index1), 8);
    }

    /**
     * Set an element of the array 'msg'
     */
    public void setElement_msg(int index1, byte value) {
        setSIntElement(offsetBits_msg(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'msg'
     */
    public static int totalSize_msg() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'msg'
     */
    public static int totalSizeBits_msg() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'msg'
     */
    public static int elementSize_msg() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'msg'
     */
    public static int elementSizeBits_msg() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'msg'
     */
    public static int numDimensions_msg() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'msg'
     */
    public static int numElements_msg() {
        return DEFAULT_MESSAGE_SIZE;
    }

    /**
     * Return the number of elements in the array 'msg'
     * for the given dimension.
     */
    public static int numElements_msg(int dimension) {
      int array_dims[] = { DEFAULT_MESSAGE_SIZE,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'msg' with a String
     */
    public void setString_msg(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_msg(i, (byte)s.charAt(i));
         }
         setElement_msg(i, (byte)0); //null terminate
    }

    /**
     * Read the array 'msg' as a String
     */
    public String getString_msg() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,DEFAULT_MESSAGE_SIZE)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_msg(i) == (char)0) break;
             carr[i] = (char)getElement_msg(i);
         }
         return new String(carr,0,i);
    }

}
